// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities. 
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if   
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure 
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;
    
    obx_model_entity(model, "Card", 1, 4543021307474494599);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 107870412950560418);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "text", OBXPropertyType_String, 2, 4182759642550461463);
    obx_model_property(model, "date_created", OBXPropertyType_Long, 3, 2893808917602724763);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "embedding", OBXPropertyType_FloatVector, 5, 6597812468947702453);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED);
    obx_model_property_index_hnsw_dimensions(model, 256);
    obx_model_property_index_hnsw_distance_type(model, OBXVectorDistanceType_Cosine);
    obx_model_property_index_hnsw_neighbors_per_node(model, 16);
    obx_model_property_index_hnsw_indexing_search_count(model, 100);
    obx_model_property_index_id(model, 2, 5350240849271719983);
    obx_model_property(model, "card_id", OBXPropertyType_String, 6, 4115431560651478346);
    obx_model_entity_last_property_id(model, 6, 4115431560651478346);
    
    obx_model_entity(model, "SetSymbol", 2, 5156128494464500038);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 6008736840270246912);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "set_code", OBXPropertyType_String, 2, 6051204396100435996);
    obx_model_property(model, "set_name", OBXPropertyType_String, 3, 7160085781048540081);
    obx_model_property(model, "variant", OBXPropertyType_String, 4, 4629637272789561220);
    obx_model_property(model, "date_created", OBXPropertyType_Long, 5, 6980494446865535055);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "embedding", OBXPropertyType_FloatVector, 6, 737399643737410699);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED);
    obx_model_property_index_hnsw_dimensions(model, 128);
    obx_model_property_index_hnsw_distance_type(model, OBXVectorDistanceType_Cosine);
    obx_model_property_index_hnsw_neighbors_per_node(model, 16);
    obx_model_property_index_hnsw_indexing_search_count(model, 100);
    obx_model_property_index_id(model, 3, 5395475422910594466);
    obx_model_entity_last_property_id(model, 6, 737399643737410699);
    
    obx_model_last_entity_id(model, 2, 5156128494464500038);
    obx_model_last_index_id(model, 3, 5395475422910594466);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
