// Code generated by ObjectBox; DO NOT EDIT.

#include "schema.obx.hpp"

const obx::Property<Card, OBXPropertyType_Long> Card_::id(1);
const obx::Property<Card, OBXPropertyType_String> Card_::card_id(2);
const obx::Property<Card, OBXPropertyType_FloatVector> Card_::embedding(3);

void Card::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Card& object) {
    fbb.Clear();
    auto offsetcard_id = fbb.CreateString(object.card_id);
    auto offsetembedding = fbb.CreateVector(object.embedding);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetcard_id);
    fbb.AddOffset(8, offsetembedding);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

Card Card::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    Card object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<Card> Card::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<Card>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void Card::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, Card& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.card_id.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.card_id.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::Vector<float>*>(8);
        if (ptr) { 
            outObject.embedding.assign(ptr->begin(), ptr->end());
        } else {
            outObject.embedding.clear();
        }
    }
}

const obx::Property<Metadata, OBXPropertyType_Long> Metadata_::id(1);
const obx::Property<Metadata, OBXPropertyType_String> Metadata_::key(2);
const obx::Property<Metadata, OBXPropertyType_String> Metadata_::value(3);

void Metadata::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Metadata& object) {
    fbb.Clear();
    auto offsetkey = fbb.CreateString(object.key);
    auto offsetvalue = fbb.CreateString(object.value);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetkey);
    fbb.AddOffset(8, offsetvalue);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

Metadata Metadata::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    Metadata object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<Metadata> Metadata::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<Metadata>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void Metadata::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, Metadata& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.key.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.key.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.value.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.value.clear();
        }
    }
}

const obx::Property<SetSymbol, OBXPropertyType_Long> SetSymbol_::id(1);
const obx::Property<SetSymbol, OBXPropertyType_String> SetSymbol_::set_code(2);
const obx::Property<SetSymbol, OBXPropertyType_FloatVector> SetSymbol_::embedding(3);

void SetSymbol::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const SetSymbol& object) {
    fbb.Clear();
    auto offsetset_code = fbb.CreateString(object.set_code);
    auto offsetembedding = fbb.CreateVector(object.embedding);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetset_code);
    fbb.AddOffset(8, offsetembedding);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

SetSymbol SetSymbol::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    SetSymbol object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<SetSymbol> SetSymbol::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<SetSymbol>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void SetSymbol::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, SetSymbol& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.set_code.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.set_code.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::Vector<float>*>(8);
        if (ptr) { 
            outObject.embedding.assign(ptr->begin(), ptr->end());
        } else {
            outObject.embedding.clear();
        }
    }
}

