// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


struct Card_;

struct Card {
    obx_id id;
    std::string card_id;
    std::vector<float> embedding;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 1; }
    
        static void setObjectId(Card& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Card& object);
    
        /// Read an object from a valid FlatBuffer
        static Card fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<Card> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, Card& outObject);
    };
};

struct Card_ {
    static const obx::Property<Card, OBXPropertyType_Long> id;
    static const obx::Property<Card, OBXPropertyType_String> card_id;
    static const obx::Property<Card, OBXPropertyType_FloatVector> embedding;
};


struct Metadata_;

struct Metadata {
    obx_id id;
    std::string key;
    std::string value;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 2; }
    
        static void setObjectId(Metadata& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Metadata& object);
    
        /// Read an object from a valid FlatBuffer
        static Metadata fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<Metadata> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, Metadata& outObject);
    };
};

struct Metadata_ {
    static const obx::Property<Metadata, OBXPropertyType_Long> id;
    static const obx::Property<Metadata, OBXPropertyType_String> key;
    static const obx::Property<Metadata, OBXPropertyType_String> value;
};


struct SetSymbol_;

struct SetSymbol {
    obx_id id;
    std::string set_code;
    std::vector<float> embedding;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 3; }
    
        static void setObjectId(SetSymbol& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const SetSymbol& object);
    
        /// Read an object from a valid FlatBuffer
        static SetSymbol fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<SetSymbol> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, SetSymbol& outObject);
    };
};

struct SetSymbol_ {
    static const obx::Property<SetSymbol, OBXPropertyType_Long> id;
    static const obx::Property<SetSymbol, OBXPropertyType_String> set_code;
    static const obx::Property<SetSymbol, OBXPropertyType_FloatVector> embedding;
};

