// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities. 
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if   
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure 
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;
    
    obx_model_entity(model, "Card", 1, 4396226563551729617);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 751083665018773679);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "card_id", OBXPropertyType_String, 2, 7026906692339299899);
    obx_model_property(model, "embedding", OBXPropertyType_FloatVector, 3, 4099408780638366301);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED);
    obx_model_property_index_hnsw_dimensions(model, 256);
    obx_model_property_index_hnsw_distance_type(model, OBXVectorDistanceType_Cosine);
    obx_model_property_index_hnsw_neighbors_per_node(model, 16);
    obx_model_property_index_hnsw_indexing_search_count(model, 100);
    obx_model_property_index_id(model, 1, 774224105752289507);
    obx_model_entity_last_property_id(model, 3, 4099408780638366301);
    
    obx_model_entity(model, "Metadata", 2, 3534185956546862336);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 7991148916819539377);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "key", OBXPropertyType_String, 2, 82651744212889932);
    obx_model_property(model, "value", OBXPropertyType_String, 3, 6286914029305820549);
    obx_model_entity_last_property_id(model, 3, 6286914029305820549);
    
    obx_model_entity(model, "SetSymbol", 3, 8919547397132275443);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 5901205378497415180);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "set_code", OBXPropertyType_String, 2, 4632725070745762585);
    obx_model_property(model, "embedding", OBXPropertyType_FloatVector, 3, 7346021300452531883);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED);
    obx_model_property_index_hnsw_dimensions(model, 128);
    obx_model_property_index_hnsw_distance_type(model, OBXVectorDistanceType_Cosine);
    obx_model_property_index_hnsw_neighbors_per_node(model, 16);
    obx_model_property_index_hnsw_indexing_search_count(model, 100);
    obx_model_property_index_id(model, 2, 6479656825031653553);
    obx_model_entity_last_property_id(model, 3, 7346021300452531883);
    
    obx_model_last_entity_id(model, 3, 8919547397132275443);
    obx_model_last_index_id(model, 2, 6479656825031653553);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
